### ISSUE TITLE
How can we make this meta repository more visible to contributors and issue creators ?

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-sdk#12]
When a contributor wants to create an issue about the sdk, it will naturally do it in the repository of the SDK he uses. But as he don't necessarily know about this repository, he can't search if the issue already exist or not. Some ways could lead him more efficiently to this repository : README.md, CONTRIBUTOR.md, Github issue template ...

**Comment by ballinette** [comment]
link added to the Readme files + issues module disabled for these repositories
