### ISSUE TITLE
No way to access to metadata via search method

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle-sdk#18]
Hello,

When using the SDK with `search` method, the SDK returns a `Document`. This object doesn't have the property `metadata` and there is no way to access to it.

Collection.js - l.465 : `var newDocument = new Document(self, doc._id, doc._source);`

The `_kuzzle_info` attribute is outside the `_source`

- [x] Javascript SDK
- [x] Java SDK
- [x] PHP SDK

**Comment by ballinette** [comment]
Still todo for PHP and Android SDKs
