### ISSUE TITLE
Adapt to the plugin authentication refactor

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-sdk#20]
Notably:
* New `createUser` (and derivatives) structure
  * Adapt `createUser` to follow the new {credentials: {...}, content: {...}}
* Adapt `getUserMapping` behavior when creating user, or add methods to call the `security:getCredentialFields` and `security:getAllCredentialFields`

**Comment by jenow** [comment]
There is nothing to do in the sdk's but we need to document the new usage of createUser so I am closing this ticket.
https://github.com/kuzzleio/documentation/issues/217
