### ISSUE TITLE
Add SDK version into volatil

### ISSUE THREAD

**Issue by jenow** [kuzzleio/kuzzle-sdk#35]
Add the SDK version into volatil of all requests

## Current status:

- [x] javascript - Done
- [x] android - Done
- [x] php - blocked by kuzzleio/kuzzle#871

**Comment by ballinette** [comment]
still missing PHP version ?

**Comment by samniisan** [comment]
@ballinette Indeed, but it's blocked by https://github.com/kuzzleio/kuzzle/issues/871

We still need to determine where to put volatile data in an HTTP context

**Comment by ballinette** [comment]
OK, i've passed this issue to `TODO` pipeline again, and updated the description with the issue dependency ;)
