### ISSUE TITLE
 Error on delete documents (deleteByQuery)

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle-sdk#4]
from https://github.com/kuzzleio/sdk-javascript/issues/157
Using kuzzle RC9 and javascript SDK  3.2.0

an error occurred when calling: 
`KuzzleDataCollection.deleteDocument({}, callback);`
with message: 
`Error: deleteByQuery must specify a body attribute "query"`

https://github.com/kuzzleio/sdk-javascript/blob/master/src/Collection.js#L223
replacing `data.body = arg;` by `data.body = {query: arg}` seem to fixes the issue

or we have to replace our call by: 
`KuzzleDataCollection.deleteDocument({query: {}}, callback);`
(and fix the SDK documentation)

Same in Android SDK: https://github.com/kuzzleio/sdk-android/blob/master/src/main/java/io/kuzzle/sdk/core/Collection.java#L604

**Comment by jenow** [comment]
Fixed in:
https://github.com/kuzzleio/sdk-android/pull/118
https://github.com/kuzzleio/sdk-javascript/pull/193

**Comment by samniisan** [comment]
Added for to PHP SDK through https://github.com/kuzzleio/sdk-php/pull/68 PR
