### ISSUE TITLE
There is no way to delete an index from the SDKs

### ISSUE THREAD

**Issue by etrousset** [kuzzleio/kuzzle-sdk#51]
There is no way to delete an index from the SDKs, this is kind of a missing feature, especially when testing scripted deployment of a kuzzle env...

**Comment by ballinette** [comment]
temporary workaround: use `kuzzle.query({controller: 'index', action: 'delete', index: '<my_index>'})`

**Comment by etrousset** [comment]
thx for the workaround!

**Comment by ballinette** [comment]
will be fixed by SDK refactoring
see https://github.com/kuzzleio/kuzzle-backlog/issues/107 / https://github.com/kuzzleio/kuzzle-backlog/issues/99
