### ISSUE TITLE
security.createUser "id" argument must be optional

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle-sdk#52]
The `security.createUser` method takes a `id` argument which is Kuzzle's unique user identifier. Since letting Kuzzle auto-generate one should be the preferred method, and since that id is not used by credentials anymore, this argument must be made optional

**Comment by ballinette** [comment]
will be fixed / deprecated by SDK refactoring
see https://github.com/kuzzleio/kuzzle-backlog/issues/88 / https://github.com/kuzzleio/kuzzle-backlog/issues/109
