### ISSUE TITLE
Error when we have two subscribes with same parameters

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle-sdk#53]
Hello,

When two subscriptions are made with the same parameters, an error is raised

```
this.channelsCollection.subscribe({}, {subscribeToSelf: true, scope: 'in'}, cb)
this.channelsCollection.subscribe({}, {subscribeToSelf: true, scope: 'in'}, cb)
```
```
Cannot read property '_id' of undefined
```

The error comes from here https://github.com/kuzzleio/sdk-javascript/blob/master/src/Room.js#L320 and this is because we delete the result from object data in the next line. The second time we pass in this function, `data.result` is undefined.

**Comment by ballinette** [comment]
will be fixed in release `6.x`

**Comment by scottinet** [comment]
since I'm refactoring parts of the `Room` object I will also fix this issue :+1:

**Comment by scottinet** [comment]
done: https://github.com/kuzzleio/sdk-javascript/pull/260
