### ISSUE TITLE
Security * - remove (create|delete|update)* methods from containers

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle-sdk#54]
For the time being, it is possible to execute the same action, either by using a SecurityDocument instance or, its related container.

i.e.:
```
kuzzle.security.createRole(role)
```
is equivalent to 
```
const role = kuzzle.security.role('id', def);
role.save();
```

While these shortcuts may be useful for documents, they are not as much for Security objects and may create some confusion.

**Comment by ballinette** [comment]
will be fixed by SDK refactoring
see https://github.com/kuzzleio/kuzzle-backlog/issues/88 / https://github.com/kuzzleio/kuzzle-backlog/issues/109
