### ISSUE TITLE
[Go/C/C++] match API structure

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle-sdk#76]
* Update the SDK structure to match Kuzzle API.
* Use raw JSON strings as input wherever objects structure is too complex or unpredictible
* For each described controller, error management should be handled: Multi-value returns in Go, Exceptions in C++, struct wrapping in C

**Comment by ballinette** [comment]
Moved to https://github.com/kuzzleio/kuzzle-backlog/issues/88
