### ISSUE TITLE
Room should be independant of Collection

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle-sdk#8]
from https://github.com/kuzzleio/sdk-javascript/issues/174 (@neolas)
> Hello,
> 
> I'm implementing a custom Plugin to manage specific realtime notifications ( filters are built plugin side based on policies, user account and other conditions).
> 
> On 3.0.1 branch, I must redefine a new class to only change :
> 
> * calls to collection.buildQueryArgs
> * parameters KuzzleDataCollection of constructor (I specify kuzzle object and query Args controller/action/collection(not requires)/index(not required) )
> 
> I think it could be really interesting to make this class more independant :)
> 
> Cheers,

**Comment by gandbox** [comment]
Private rooms topic

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/kuzzle-backlog #111](https://github.com/kuzzleio/kuzzle-backlog/issues/111) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ballinette** [comment]
Issue moved to [kuzzleio/sdk-javascript #283](https://github.com/kuzzleio/sdk-javascript/issues/283) via [**ZenHub**](https://www.zenhub.com/)
